# This is a basic workflow to help you get started with Actions

name: phpunit

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest 
    
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: update ubuntu
      run: sudo apt-get update
      
    - name: update sqlite3
      run: sudo apt-get install sqlite3 libsqlite3-dev
      
    - name: checksqlite version
      run: sqlite3 --version
    
    - name: install sqlite manually
      run: |
        wget https://launchpad.net/ubuntu/+archive/primary/+sourcefiles/sqlite3/3.32.2-2/sqlite3_3.32.2.orig.tar.xz       
        tar xvf sqlite3_3.32.2.orig.tar.xz 
        cd sqlite3-3.32.2/
        sudo ./configure
        sudo make
        sudo make install
    
    - name: checksqlite version2
      run: sqlite3 --version
    
               
    - name: composer update
      run: composer update
     # Composer.
    - name: composer settings
      run: |
        export PATH="$HOME/.composer/vendor/bin:$PATH"
        echo $PATH  

    - name: install drupal
      run:  composer create-project drupal/recommended-project:8.8.0 drupal  

    - name: check sqlite file
      run: ls -la drupal/web/sites/
  
    - name: drupal composer update
      run: cd drupal && composer update && composer require drush/drush && composer require phpunit/phpunit && cd -
      
  
    #vendor/drush/drush/drush site:install standard -vvv --db-url='sqlite://sites/default/files/.ht.sqlite'
    - name: install drupal base with sqlite
      run: |              
        cd drupal        
        vendor/drush/drush/drush site:install standard -vvv --db-url='sqlite://tmp/test.db'
        cd -
      
    - name: copy plugin to drupal
      run: |
        mkdir -p drupal/web/modules/arche-gui
        for d in $(pwd)/*; do ln -s "$d" "drupal/web/modules/arche-gui"; done
    
    - name: check directories
      run: |
        ls -la  
        cd drupal/web/modules && ls -la
        cd arche-gui && ls -la
        
   
    - name: start web server
      run: |
        cd drupal && vendor/drush/drush/drush runserver 127.0.0.1:8080 &
        until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done  
        
    - name: test
      run: |
        mkdir -p build/logs
        ./drupal/vendor/phpunit/phpunit/phpunit --configuration ./drupal/web/modules/arche-gui/phpunit.xml 
        
  
